name: mobx_sm
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  get_it: ^7.6.0
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  riverpod: ^2.3.6
  stacked: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
